service: terra-less

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${env:STAGE}
  region: us-east-2
  apiGateway:
    restApiId: ${ssm:/terra_less/${env:STAGE}/api_gateway/id}
    restApiRootResourceId: ${ssm:/terra_less/${env:STAGE}/api_gateway/root_resource_id}

functions:
  service1:
    handler: src/handler.handler
    events:
      - http: 
          method: ANY
          path: /service1/{any+}

plugins:
  - serverless-dotenv-plugin