name: Deploy

on:
  push:
    branches: [master]
env:
  ENV_STAGE: dev
  RESOURCE_NAME: terra-less-provision
  PROJECT_NAME: terra-less
  AWS_REGION: us-east-2

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Script Permissions
        id: terraform_script_permissions
        run: chmod 700 ./scripts -R
      - name: Configure and Run Terraform state management prerequisites
        id: terraform_run_state
        run: ./init_state.sh ${{ env.RESOURCE_NAME }} ${{ env.AWS_REGION }}
        working-directory: ./scripts
      - name: Transform Infrastructure Values
        working-directory: ./src
        id: transform_infrastructure_values
        run: |
          sed -i "s|{{AWS_REGION}}|${{ env.AWS_REGION }}|g" "variables.tf"
          sed -i "s|{{PROJECT_NAME}}|${{ env.PROJECT_NAME }}|g" "variables.tf"
          sed -i "s|{{ENVIRONMENT}}|${{ env.ENV_STAGE }}|g" "variables.tf"
          sed -i "s|{{AWS_REGION}}|${{ env.AWS_REGION }}|g" "backend.tf"
          sed -i "s|{{RESOURCE_NAME}}|${{ env.RESOURCE_NAME }}|g" "backend.tf"
      - name: "Terraform Init"
        working-directory: ./src
        id: terraform_init
        run: terraform init
      - name: "Terraform Plan"
        working-directory: ./src
        id: terraform_plan
        run: terraform plan
      - name: "Terraform Apply"
        working-directory: ./src
        id: terraform_apply
        run: terraform apply -auto-approve